### ISSUE TITLE
Create / Delete index

### ISSUE THREAD

**Issue by mrbenosborne** [philippe-vandermoere/terraform-provider-algolia#9]
Hi,

Good work on this.

Does it provide a resource of "index", so terraform can create/delete indexes?

**Comment by philippe-vandermoere** [comment]
Hi

I started to look the implementation of the resource_algolia_index in the provider but the list of [parameters ](https://www.algolia.com/doc/api-reference/settings-api-parameters/) for creating/updating the algolia index is long. 

I propose to start with the following list:
 - searchableAttributes
 - attributesForFaceting
 - unretrievableAttributes
 - attributesToRetrieve
 - ranking
 - customRanking
 - replica
 - maxValuesPerFacet
 - sortFacetValuesBy
 - hitsPerPage
 - paginationLimitedTo

Is this enough for your need ?

**Comment by mrbenosborne** [comment]
Hi,

Yes of course, let me know if you need a hand, I'd be happy to jump on and do some.
